FROM python:3.11-bookworm
RUN pip install dbt-core==1.7.18
RUN pip install dbt-mysql==1.7.0
RUN pip install dbt-postgres==1.7.18
RUN pip install dbt-snowflake==1.7.5
# RUN mkdir /usr/src
WORKDIR /usr/src
CMD ['bash']